const assert = require('assert'), U = require('../results/dashboard/chart-util.js');
assert.equal(U.metaKey('005930.KS', 'D'), '005930.KS#D');
assert(U.validFrame({ symbol: 'A', candles: [{ time: '2026-01-01' }] }));
assert(!U.validFrame({ symbol: 'A', candles: [] }));
assert(!U.validFrame({ symbol: 1, candles: [{}] }));
assert(!U.validFrame(null));
const frames = {symbol:'A',candles:[{time:'D'}],weekly:{candles:[{time:'W'}]},monthly:{candles:[{time:'M'}]}};
assert.equal(U.selectFrame(frames,'D'),frames);
assert.equal(U.selectFrame(frames,'W'),frames.weekly);
assert.equal(U.selectFrame(frames,'M'),frames.monthly);
assert.equal(U.selectFrame({candles:[{}]},'W'),null,'missing weekly must not use daily');
assert.equal(U.selectFrame({candles:[{}]},'M'),null,'missing monthly must not use daily');
const h4={tf:'H4',candles:[{time:123}]};
assert.equal(U.selectFrame(frames,'H4',h4),h4);
assert.equal(U.selectFrame(h4,'H4'),h4);
const f = { candles: [{ time: '2026-06-01' }, { time: '2026-08-15' }, { time: '2026-09-07' }] };
assert.equal(U.latestTime(f), '2026-09-07');
assert.equal(U.latestTime({ candles: [] }), null);
assert.equal(U.rangeStartIdx(f, 'ALL'), 0);
assert.equal(U.rangeStartIdx({ candles: [] }, '3M'), 0);
assert.equal(U.rangeStartIdx(f, '1M'), 1);
assert.equal(U.rangeStartIdx(f, '3M'), 1);
assert.equal(U.rangeStartIdx(f, '1Y'), 0);
assert.equal(U.bidxOf(f, '2026-08-15'), 1);
assert.equal(U.bidxOf(f, '2026-01-01'), -1);
const arr = [{ statusId: 'a' }, { statusId: 'a' }, null, {}, { statusId: 'b' }, { statusId: 'b' }, { statusId: 'c' }];
assert.deepEqual(U.obsTransitions(arr).map(x => x.i), [0, 4, 6]);
const labels = U.pickObsLabels(f, arr, 5);
assert.deepEqual(labels.map(x => x.i), [0, 5]);
assert(labels.find(x => x.i === 5).showText);
assert(labels.find(x => x.i === 0).showText);
assert(!labels.some(x => x.i === 4));
// Oscillating states must not put a circle on every candle. Selection adds
// its own point without moving the fixed full-history sample.
const noisy=Array.from({length:200},(_,i)=>({statusId:i%2?'watch':'breaklow'}));
const before=JSON.stringify(noisy),fixed=U.pickObsLabels(f,noisy,null);
assert.equal(fixed.length,17);
assert(fixed.every((p,i)=>!i||p.i-fixed[i-1].i>=12));
const selected=U.pickObsLabels(f,noisy,197);
assert.deepEqual(selected.filter(p=>p.i!==197).map(p=>p.i),fixed.map(p=>p.i));
assert(selected.find(p=>p.i===197).showText);
assert.equal(JSON.stringify(noisy),before);
assert.equal(String(U.barDateVal('2026-09-07')).slice(0, 15), String(new Date('2026-09-07T00:00:00')).slice(0, 15));
console.log('Chart util: helper and D/W/M/H4 frame selection guards passed');
