const assert=require('assert'),{evaluate}=require('../results/dashboard/entry-model');
const {assess}=require('../results/dashboard/chart-timing');
const now=Date.now(),live=assess({now,source:'toss',fetchedAt:new Date(now).toISOString(),marketSession:{state:'open'},snapshotEligible:true,enabled:true,barAsOf:null});
const closed=assess({now,source:'toss',fetchedAt:new Date(now).toISOString(),marketSession:{state:'closed'},confirmed:true});
const frame={candles:[{time:'2026-09-01',close:100},{time:'2026-09-02',close:102},{time:'2026-09-03',close:108}],state:[{sigA:'entry',sigB:'none',sigC:'entry',sigF:'entry',atr14:10},{sigA:'none',sigB:'entry',sigC:'entry',sigF:'none',atr14:10},{sigA:'none',sigB:'none',sigC:'entry',sigF:'entry',atr14:10}],marks:{}};
const run=x=>evaluate({frame,index:0,timing:closed,...x});
assert.equal(run({}).code,'candidate');
assert.equal(run({timing:live}).label,'봉 확정 대기');
assert.equal(run({timing:{judgmentReady:false,message:'조회 실패'}}).code,'blocked');
assert.equal(run({index:2,selected:['C']}).code,'chase');
assert.equal(run({index:1,selected:['A','B'],mode:'all'}).matched,false);
assert.equal(run({index:1,selected:['A','B'],mode:'any'}).matched,true);
assert.equal(run({selected:[]}).code,'blocked');
assert.equal(run({historical:true}).code,'historical');
assert(run({selected:['C','F']}).combinationNote);
const baseline=JSON.stringify(run({historical:true}));frame.state[2].sigF='exit';frame.candles[2].close=900;
assert.equal(JSON.stringify(run({historical:true})),baseline,'Future bars must not change historical judgment');
assert.equal(run({index:2}).setupDecision.code,'avoid');
const missing={candles:frame.candles,state:[{sigF:'entry',atr14:null}]};assert.equal(run({frame:missing}).code,'blocked');
assert.equal(live.realtimeReady,false);
for(const selected of [['A'],['C'],['F']])assert.equal(run({selected,timing:live}).label,'봉 확정 대기');
assert.equal(run({selected:['B'],index:1,timing:live}).label,'봉 확정 대기');
assert.equal(run({selected:['B'],timing:live}).code,'wait');
assert.equal(run({index:2,timing:live}).code,'avoid');
console.log('Entry decisions: 12 regression assertions passed');
