'use strict';
const assert=require('node:assert/strict'),Cache=require('../results/dashboard/low-structure-cache'),Context=require('../results/dashboard/low-entry-context'),View=require('../results/dashboard/low-structure-panel'),{sample,day}=require('./low_entry_sample');
const b=sample('H'),frame={symbol:'TEST',tf:'D',candles:b,source:'toss',fetchedAt:'2026-01-27T15:00:00Z',marketSession:{state:'closed'},lastConfirmedTime:day(26),confirmed:true};
const run=extra=>Context.evaluate({frame,index:26,symbol:'TEST',tf:'D',now:Date.parse('2026-01-27T15:00:00Z'),...extra});
const first=run();assert.equal(first.decision.code,'candidate');assert.equal(first.decision.index,26);assert.equal(first.analysis.basis,day(26));
assert.equal(run({lastError:{kind:'failed'}}).decision.code,'blocked');
assert.equal(run({frame:{...frame,lastConfirmedTime:null}}).decision.code,'blocked');
const future={...frame,lastConfirmedTime:day(40),fetchedAt:'2030-01-01T00:00:00Z',marketSession:{state:'open'}};
const past=run({historical:true}),other=run({frame:future,historical:true});assert.deepEqual(past.analysis,other.analysis);assert.equal(past.decision.code,'historical');assert.equal(past.decision.setupDecision.code,'candidate');
assert.equal(run({frame:{...frame,tf:'W'},tf:'W'}).decision.code,'blocked');
assert.equal(run({frame:{...frame,marketSession:{state:'open'},snapshotEligible:true},index:27,enabled:true}).decision.code,'wait','forming bar cannot emit green');
assert.equal(run({frame:{...frame,marketSession:{state:'open'},snapshotEligible:true,fetchedAt:'2026-01-27T10:00:00Z'},index:27}).decision.code,'blocked');
const invalidCache=Cache.create(20),base={symbol:'TEST',timeframe:'D',candles:b.map((c,i)=>i===26?{...c,volume:null}:c),observedThrough:day(26),confirmedThrough:day(26)};
assert.equal(invalidCache.analyze(base).status,'ready');assert.equal(invalidCache.analyze({...base,candles:b.map((c,i)=>i===26?{...c,volume:NaN}:c)}).status,'invalid-data');assert.equal(invalidCache.analyze({...base,version:''}).status,'invalid-data');assert.equal(invalidCache.analyze({...base,params:{maxAtr:undefined}}).status,'invalid-data');
const cache=Cache.create(20),input={symbol:'TEST',timeframe:'D',candles:b,observedThrough:day(26),confirmedThrough:day(26),sourceRevision:'a'};
const original=JSON.stringify(b),x=cache.analyze(input);assert(Object.isFrozen(x.current.H));assert.strictEqual(cache.analyze(input),x);assert.equal(cache.stats().calculations,1);
for(const changed of [{sourceRevision:'b'},{params:{maxAtr:1}},{confirmedThrough:day(25)},{candles:b.slice(1)},{candles:b.map((c,i)=>i===26?{...c,volume:c.volume+1}:c)},{candles:b.map((c,i)=>i===26?{...c,close:c.close-.1}:c)}])assert.notStrictEqual(cache.analyze({...input,...changed}),x);
assert.equal(JSON.stringify(b),original);
const corrected=cache.analyze({...input,candles:b.map((c,i)=>i===26?{...c,volume:c.volume+2}:c)});assert.equal(corrected.revision.kind,'source-correction');assert.equal(corrected.revision.notify,false);assert(corrected.revision.changedIds.length>0);
const reverted=cache.analyze(input);assert.equal(reverted.revision.kind,'source-correction');assert.equal(reverted.revision.notify,false);
const cut=cache.analyze({...input,candles:b.slice(1)});assert.equal(cut.revision.firstBarChanged,true);
for(let i=0;i<25;i++)cache.analyze({...input,symbol:'S'+i});assert.equal(cache.stats().frames,20);
for(let i=13;i<40;i++)cache.analyze({...input,observedThrough:day(i),confirmedThrough:day(i)});
const current=cache.stats();assert(current.frames<=20);assert(current.prefixes<=20*32);
const shown=View.visible(first.analysis),s=shown.find(s=>s.id===first.decision.structureId),markers=View.markers(s);
assert.equal(markers.length,3);assert.equal(markers.find(m=>m.shape==='arrowUp').time,s.signalAt);assert.equal(View.markers(s).length,3);assert.equal(View.geometry(s).length,2);
assert(markers.filter(m=>m.shape==='circle').every(m=>m.text.includes('확인')));
assert.equal(View.visible({...first.analysis,observedThrough:'2026-10-06'}).length,0);
console.log('Low context: confirmed/live/past gates, cache correction/LRU and one-structure markers passed');
