const assert=require('node:assert/strict');
const W=require('../results/dashboard/pattern-window.js');
const {view}=require('../results/dashboard/flag-panel.js');
const {observations,colors}=require('../results/dashboard/chart-legend.js');
assert.equal(W.start('2026-05-31'),'2026-02-28');assert.equal(W.start('2024-05-31'),'2024-02-29');assert.equal(W.start('2026-01-31'),'2025-10-31');
const events=[{anchorTime:'2026-06-07',confirmedBarTime:'2026-09-07'},{anchorTime:'2026-06-06',confirmedBarTime:'2026-09-07'},{anchorTime:'2026-07-01',confirmedBarTime:'2026-09-08'}];
assert.deepEqual(W.filter(events,'2026-09-07'),[events[0]]);
const analysis={enabled:true,sourceStatus:'ready',timeline:[{barTime:'2026-09-07',confirmed:true,patterns:[{structureStartTime:'2026-06-06',status:'forming'},{structureStartTime:'2026-06-07',status:'forming'}]}],recentEvents:events};
const before=JSON.stringify(analysis),v=view(analysis,'D',null,false);
assert.equal(v.patterns.length,1);assert.equal(v.events.length,1);assert.equal(JSON.stringify(analysis),before);
assert.equal(v.window.start,'2026-06-07');
assert.equal(observations.length,7);assert.equal(colors.uptrend,'#2E7D32');assert.equal(colors.breaklow,'#C62828');assert.equal(colors.watch,'#B26A00');
const end=Date.UTC(2026,4,31,12)/1000,begin=Date.UTC(2026,1,28,12)/1000;
assert.equal(W.start(end),begin);
const h4={enabled:true,timeframe:'H4',sourceStatus:'ready',provisionalEligible:true,timeline:[{barTime:end,confirmed:false,status:'ready',patterns:[{structureStartTime:begin,status:'breakout-pending'}]}],recentEvents:[{anchorTime:begin,confirmedBarTime:end,timeframe:'H4'}]};
assert.equal(view(h4,'H4',null,false).patterns[0].status,'breakout-pending');
assert.equal(view(h4,'H4',null,true).patterns[0].status,'paused');
assert.equal(view(h4,'D',null,false).status,'unsupported');
assert.equal(view(analysis,'H4',null,false).status,'unsupported','daily evidence must never leak into H4');
assert.equal(W.within({anchorTime:begin-14400,confirmedBarTime:end},end),false);
console.log('Calendar window, structural start, immutable view and marker legend passed');
